name: Environment Variables
on: [workflow_dispatch]

jobs:
    build:
      env:
        MyVariable: 'Hello, World'      
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./script.ps1 -Parameter1 "Setup Parameter"
          shell: pwsh
        - name: Print
          run: |
           echo "variable from shell environment : $MyVariable"
