name: Environment Variables
on: [workflow_dispatch]

jobs:
    build:
      env:
        MyVariable: 'Hello, World'      
      name: Run Script
      runs-on: ubuntu-latest
      outputs:
        var_Val2: ${{ steps.set-Val2.outputs.Val2 }}
      steps:
        - name: Val2
          id: set-Val2
          run: >-
            echo "Val2=Moe" >> $GITHUB_OUTPUT
        - name: Print
          run: |
               echo "Val2: ${{ needs.build.outputs.var_Val2 }}"
    job1:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
          - name: Print2
            run: |
               echo "Val2: ${{ needs.build.outputs.var_Val2 }}"
    job2:
        runs-on: ubuntu-latest
        steps:
          - name: Chekout
            uses: actions/checkout@v4
          - name: write
            shell: pwsh
            run: |
              echo "This is my output" >> $GITHUB_OUTPUT
          - name: read
            shell: pwsh
            run: |
              $output = Get-Content $GITHUB_OUTPUT
              Write-Output "This output is : $output" 
