name: Environment Variables
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./script.ps1 -Parameter1 "Setup Parameter"
          shell: pwsh
          env:
            MyVariable: 'Hello, World'
