name: Environment Variables
on: [workflow_dispatch]

jobs:
    build:
      env:
        MyVariable: 'Hello, World'      
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./script.ps1 -Parameter1 "Setup Parameter"
          shell: pwsh
        - name: Print
          run: |
           echo "variable from shell environment : $MyVariable"
    job1:
        env:
          GITHUB_OUTPUT: 'Dummy'
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
          output1: ${{ steps.step1.outputs.test }}
          output2: ${{ steps.step2.outputs.test }}
        steps:
          - id: step1
            run: echo "test=hello" >> "$output1"
          - id: step2
            run: echo "test=world" >> "$output2"
          - id: step3
            run: echo "${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}"
