name: Environment Variables
on: [workflow_dispatch]

jobs:
    build:
      env:
        MyVariable: 'Hello, World'      
      name: Run Script
      runs-on: ubuntu-latest
      outputs:
        var_Val2: ${{ steps.set-Val2.outputs.Val2 }}
      steps:
        - name: Val2
          id: set-Val2
          run: >-
            echo Val2=Moe >> %GITHUB_OUTPUT%
    job1:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
          - name: Print
            run: |
               echo "Val2: ${{ needs.build.outputs.var_Val2 }}"
