name: Environment Variables
on: [workflow_dispatch]

jobs:
    build:
      env:
        MyVariable: 'Hello, World'      
      name: Run Script
      runs-on: ubuntu-latest
      outputs:
        var_Val2: ${{ steps.set-Val2.outputs.Val2 }}
      steps:
        - name: Val2
          id: set-Val2
          run: >-
            echo "Val2=Moe" >> $GITHUB_OUTPUT
        - name: Print within steps
          id: Print
          run: |
               echo "Val2: ${{ steps.set-Val2.outputs.Val2 }}"
    job1:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
          - name: Print between jobs
            run: |
               echo "Val2: ${{ needs.build.outputs.var_Val2 }}"
    job2:
        runs-on: ubuntu-latest
        steps:
         - name: "Example output creation"
           id: "my_step"
           run: |
            my_var="Hello World !"
            echo "Output [$my_var]"
            echo "my_var=$my_var" >> $GITHUB_OUTPUT    
         - name: "Example output call between steps"
           run: |
                echo "Output [${{steps.my_step.outputs.my_var}}]"
    job3:
        runs-on: ubuntu-latest
        steps:
         - name: "Run Powershell"
           id: "my_step"
           run: ./resulttesting.ps1
       #  - name: "Check result of powershell"
        #   run: |
         #       echo "${{steps.my_step.outputs.script-output}}"
