name: Exit Code
on: [workflow_dispatch]

env:
 stage_result: 'True' 

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: |
            $stage_result =./resulttesting.ps1
          shell: pwsh
        - name: Testing eco of repo  variables
          run: |
           echo "result : $stage_result"


  # run: ./script.ps1 -ExitCode
