name: Exit Code
on: [workflow_dispatch]

env:
 stage_result: 'True' 

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Executing script block
          run: |
           Invoke-Command -ScriptBlock {
             ./resulttesting.ps1 
            #$env:stage_result = Get-Content ./resulttesting.ps1
           }
          continue-on-error: true
          shell: pwsh
        - name: Script block result
          run: echo $env:stage_result
          shell: pwsh
    build1:
      needs: build
      name: Run Script1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script1
          run: echo "Hello"
          shell: pwsh
    job3:
        name: Run Script2
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v1
           - name: script
             run: ./resulttesting.ps1
       #  - name: "Check result of powershell"
        #   run: |
         #       echo "${{steps.my_step.outputs.script-output}}"

  # run: ./script.ps1 -ExitCode
