name: Exit Code
on: [workflow_dispatch]

env:
 stage_result: 'True' 

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      outputs:
        var_Val2: ${{ steps.set-Val2.outputs.Val2 }}
      steps:
       # - uses: actions/checkout@v1
        - name: Executing script block
          id: set-Val2
          run: |
             $result = Invoke-Command -ScriptBlock {
               ./resulttesting.ps1 
              }
              echo $stage_result
          #continue-on-error: true
          shell: pwsh
        - name: Script block result
          run: |
               echo "Val2: ${{ steps.set-Val2.outputs.Val2 }}"
          shell: pwsh
      

  # run: ./script.ps1 -ExitCode
