name: Exit Code
on: [workflow_dispatch]

env:
 stage_result: 'True' 

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      outputs:
        var_Val2: ${{ steps.set-Val2.outputs.Val2 }}
      steps:
        - name: Val2
          id: set-Val2
          run: |
              $result = Invoke-Command -ScriptBlock {
              ./resulttesting.ps1 
              }
              
              echo "Val2=Moe" >> $GITHUB_OUTPUT
        - name: Print within steps
          id: Print
          run: |
             echo "Val2: ${{ steps.set-Val2.outputs.Val2 }}"
      

  # run: ./script.ps1 -ExitCode
