name: Exit Code
on: [workflow_dispatch]

env:
 stage_result: 'True' 

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: script
          run: ./resulttesting.ps1 -OutputVariable my-output-variable
          continue-on-error: true
          shell: pwsh
        - name: Script1
          run: echo ${{ steps.script.outputs.my-output-variable}}
          shell: pwsh
    build1:
      needs: build
      name: Run Script1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script1
          run: echo "Hello"
          shell: pwsh

  # run: ./script.ps1 -ExitCode
