name: Exit Code
on: 
 workflow_dispatch:
  inputs:
      Application:
        description: 'Application Name'
        required: true
        default: 'DTS'
        type: choice
        options:
        - DTS
        - Licensing
      runtype:
        description: 'Run Type'
        required: true
        default: 'build'
        type: choice
        options:
        - build
        - staging
        - production
        
env:
 stage_result: 'True' 
 environment_shortName: if (${{inputs.runtype}} -eq 'build') then 'dev' else ${{inputs.runtype}}

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      outputs:
        var_Val2: ${{ steps.set-Val2.outputs.Val2 }}
      steps:
        - uses: actions/checkout@v1
        - name: Executing script block
          id: set-Val2
          run: |
              #stage_result="MyTestResourceGroup"
              #echo "Val2=$stage_result" >> $GITHUB_OUTPUT
              #echo "Val2=TETE" >> $GITHUB_OUTPUT
               echo ${{ env.environment_shortName}}
          #continue-on-error: true
          shell: pwsh
        - name: Script block result
          run: |
               echo "Val2: ${{ steps.set-Val2.outputs.Val2 }}"
               echo "variable from shell environment :  ${{ env.stage_result}}"
          shell: pwsh
      

  # run: ./script.ps1 -ExitCode
