name: Exit Code
on: [workflow_dispatch]

env:
 stage_result: 'True' 

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: script
          run: ./script.ps1 -Parameter1 ([ref]${{ env.stage_result }})
          continue-on-error: true
          shell: pwsh
        - name: Script1
          run: echo "$stage_result"
          shell: pwsh
    build1:
      needs: build
      name: Run Script1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script1
          run: echo "Hello"
          shell: pwsh
    job3:
        name: Run Script2
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v1
           - name: script
             run: ./resulttesting.ps1
       #  - name: "Check result of powershell"
        #   run: |
         #       echo "${{steps.my_step.outputs.script-output}}"

  # run: ./script.ps1 -ExitCode
