# This is the name of workflow
name: Package Image creator
on: [workflow_dispatch]

# This block is used to setup global environment variables shared across enitre workflow
env:
 env_var: ${{ vars.MESSAGE_REPO }}
 sample_credentials: ${{ secrets.SAMPLE_SECRET }}
 #sample_secret_ID: ${{ fromJSON(secrets.AZURE_CRED)['clientId'] }}
 
# Jobs are listed to be run of GitHub runners. 
jobs:
    # This job is to validate all the input values used in workflow.
    Validate-Inputs:
      if: ${{contains(vars.job_switches, 'validate') }} 
      name: Validate Inputs
      runs-on: ubuntu-latest
      environment: development
      steps:
        - uses: actions/checkout@v1
        - name: Script using  repo variable
          run: .\script.ps1 -Parameter1 ${{ env.env_var }}
          shell: pwsh
        - name: Script using Environment variable
          run: .\script.ps1 -Parameter1 ${{ vars.MESSAGE }}
          shell: pwsh
        - name: Testing eco of repo  variables
          run: |
           echo "variable from shell environment : $env_var"
           
    # This job is to setup and run packer to create managed image.       
    Setup-Run-Packer:
      if: ${{contains(vars.job_switches, 'packer') }} 
      needs: Validate-Inputs
      name: Run packer
   #   continue-on-error: true
      runs-on: ubuntu-latest
      environment: development
      steps:
        - name: Run packer
          run: |
           echo "Run packer on environment : $env_var" 
           #exit 1
        - name: Run packer 2
          run: |
           echo "Run packer 2"
        - name: Run packer 3
          run: |
           echo "Run packer 3"
        - name: Failure cleanup Task
          if: always()
          run: |
           echo "Failure cleanup"

    # This job is to do post validation on the image created as part of packer.  
    Post-Validation:
      if: ${{contains(vars.job_switches, 'packer') }} 
      needs: Setup-Run-Packer
      name: Validate Image
      runs-on: ubuntu-latest
      environment: development
      steps:
        - name: Testing Image Validation Script
          run: |
           echo "Image Validation Script on environment : $env_var"

    # This job is to publish the image in the Azure compute gallery.  
    Publish-image:
      if: ${{contains(vars.job_switches, 'publish') }} 
      needs:
      - Post-Validation
      name: Publish Image
      runs-on: ubuntu-latest
      environment: development
      steps:
        - name: Testing Image Publish Script
          run: |
           echo "Image Publish Script on environment : $env_var"
    
    # This job is to publish the image in the Azure compute gallery.  
    sample-parallel:
      #if: ${{contains(vars.job_switches, 'skip') }} 
      needs: Setup-Run-Packer
      name: Sample Parallel
      runs-on: ubuntu-latest
      environment: development
      steps:
        - name: Testing Image Publish Script
          run: |
           echo "Example of Parallel"
