name: Parameters
on: [workflow_dispatch]
env:
 env_var: ${{ vars.MESSAGE }}
jobs:    
    build:
      name: Run Script
      runs-on: ubuntu-latest
      environment: development
      steps:
        - uses: actions/checkout@v1
        #- name: Script using  repo variable
         # run: .\script.ps1 -Parameter1 $MESSAGE_TEST
         # shell: pwsh
        - name: Script using Environment variable
          run: .\script.ps1 -Parameter1 ${{ vars.MESSAGE }}
          shell: pwsh
        - name: Use variables
          run: |
           echo "repository variable : $REPOSITORY_VAR"
           echo "variable from shell environment : $env_var"
        
